### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by geoffroyO** [rashmi05pathak/Ano-swinMAE#1]
Hi, thank you for making the code available.

As I understand it your function "window_masking" randomly mask the patches for the training step. But how should I do when I want to infer an image? In the window_masking_ method I see that there are multi sparse_keep tensors should I use them?

Thanks!

**Comment by rashmi05pathak** [comment]
Hi Geoffroy, Thanks for raising the issue. I have updated the inference folder with the file named evaluation_brats21 which contains the code to infer the model. Here you can see how I have used the window_masking_ method. I will try to document the code properly so that there will not be any confusion.

regards,
Rashmi
